USE TEST1;

CREATE TABLE `TEST`(
`FNAME` VARCHAR (20) NOT NULL,
`MNAME` CHAR NULL,
`LNAME` CHAR NULL,
`SSN` CHAR (9) NOT NULL,
`BDATE` DATE,
`ADDRESS` VARCHAR (50),
`SEX` CHAR NULL,
`SALARY` DECIMAL (10,2) NULL,
`SUSN` CHAR(9) NULL,
`DNO` INT NOT NULL,
PRIMARY KEY (`SSN`));

RENAME TABLE `TEST` TO `COMPANY`;

CREATE TABLE `DEPARTMENT` (
`DNAME` VARCHAR (15),
`DNUM` INT NOT NULL,
`MGR_SSN` CHAR(9),
`MGR_STT_DT` DATE NULL,
PRIMARY KEY (`DNUM`));

USE TEST1;

CREATE TABLE `DEPTLOC`(
`DNUM` INT NOT NULL,
`DLOC` VARCHAR(50) NOT NULL,
PRIMARY KEY (`DNUM`, `DLOC`)
);

CREATE TABLE `PROJS`
(
`PNAME` VARCHAR (10)NOT NULL,
`PNUM` INT (5) NOT NULL,
`PLOC` VARCHAR (30) NULL,
`DNUM` INT NOT NULL,
PRIMARY KEY (`PNUM`),
UNIQUE (`PNAME`));



